---
title: "Workflow for using retrieveR"
author: "John Brandt"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Workflow}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


## Info

This vignette walks the user through applying the neural embedding NLP approach to a novel set of PDF documents. We use a sample corpus of 10 peer-reviewed academic journal articles about restoration. 

## Downloading data

```{r}
library(retrieveR)
download_example()
```


## Running OCR

The figure sizes have been customised so that you can easily put two images side-by-side. 

```{r}
run_ocr("pdfs")
```

## Make corpus

```{r}
corpus <- make_corpus("pdfs")
```


```{r, fig.show='hold'}
download_embeddings()
locations <- create_locations(corpus, "embeddings.bin")
```

```{r}
interactive_report(query="market risks", locations="embeddings.rds", data=corpus, type = "html")
```

